### ISSUE TITLE
SuspensionDeadlockException when unparsing 2 message document

### ISSUE THREAD

**Issue by mbeckerle** [DFDLSchemas/mil-std-2045#28]
See test_2045_D1_all_fields_x2u

**Comment by stevedlawrence** [comment]
The issue to track this in Daffodil is [DAFFODIL-2717](https://issues.apache.org/jira/browse/DAFFODIL-2717).

This has been fixed in Daffodil and will be part of the 3.4.0 release.

**Comment by mbeckerle** [comment]
PR https://github.com/DFDLSchemas/mil-std-2045/pull/35 uses the fixed Daffodil, so once merged is the fix for this issue.

**Comment by mbeckerle** [comment]
Fixed in commit d6b289c07e77be5ee95b64fd3951596998259458
Note: On dev branch, not main branch. Because it depends on a Daffodil unreleased version (aka snapshot)
